// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedHasRolledToBU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedHasRolledToBU));
        
        string IMigrationMetadata.Id
        {
            get { return "201605131505249_AddedHasRolledToBU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
